import { MarketPair } from '../../../types/ecnTrading';

export const INITIAL_MARKET_PAIRS: MarketPair[] = [
  {
    id: 'ecoin-usdt',
    baseSymbol: 'ECOIN',
    quoteSymbol: 'USDT',
    displayPair: 'E-Coin / USDT',
    price: 0.0102,
    priceChange24h: 2.41,
    liquidityUsd: 450000,
    volume24hUsd: 125000,
    aiSignal: 'BUY',
    pancakeUrl: 'https://pancakeswap.finance/swap?inputCurrency=BNB&outputCurrency=ECOIN',
    isLive: true,
  },
  {
    id: 'usdt-ecoin',
    baseSymbol: 'USDT',
    quoteSymbol: 'ECOIN',
    displayPair: 'USDT / E-Coin',
    price: 98.04,
    priceChange24h: -2.35,
    liquidityUsd: 450000,
    volume24hUsd: 125000,
    aiSignal: 'SELL',
    pancakeUrl: 'https://pancakeswap.finance/swap?inputCurrency=ECOIN&outputCurrency=USDT',
    isLive: true,
  },
  {
    id: 'ecoin-bnb',
    baseSymbol: 'ECOIN',
    quoteSymbol: 'BNB',
    displayPair: 'E-Coin / BNB',
    price: 0.000017,
    priceChange24h: 1.82,
    liquidityUsd: 320000,
    volume24hUsd: 89000,
    aiSignal: 'STRONG_BUY',
    pancakeUrl: 'https://pancakeswap.finance/swap?inputCurrency=BNB&outputCurrency=ECOIN',
    isLive: true,
  },
  {
    id: 'bnb-ecoin',
    baseSymbol: 'BNB',
    quoteSymbol: 'ECOIN',
    displayPair: 'BNB / E-Coin',
    price: 58823.5,
    priceChange24h: -1.79,
    liquidityUsd: 320000,
    volume24hUsd: 89000,
    aiSignal: 'HOLD',
    pancakeUrl: 'https://pancakeswap.finance/swap?inputCurrency=ECOIN&outputCurrency=BNB',
    isLive: true,
  },
  {
    id: 'ecoin-eusd',
    baseSymbol: 'ECOIN',
    quoteSymbol: 'EUSD',
    displayPair: 'E-Coin / EUSD',
    price: 0.0101,
    priceChange24h: 2.17,
    liquidityUsd: 280000,
    volume24hUsd: 64000,
    aiSignal: 'BUY',
    pancakeUrl: 'https://pancakeswap.finance/swap?inputCurrency=EUSD&outputCurrency=ECOIN',
    isLive: true,
  },
  {
    id: 'eusd-ecoin',
    baseSymbol: 'EUSD',
    quoteSymbol: 'ECOIN',
    displayPair: 'EUSD / E-Coin',
    price: 99.01,
    priceChange24h: -2.12,
    liquidityUsd: 280000,
    volume24hUsd: 64000,
    aiSignal: 'SELL',
    pancakeUrl: 'https://pancakeswap.finance/swap?inputCurrency=ECOIN&outputCurrency=EUSD',
    isLive: true,
  },
];